apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-hello-world
spec:
  steps:
  - name: list-files
    image: alpine
    command:
    - ls
    args:
    - -ahl
  - name: echo
    image: alpine
    command:
    - echo
    args:
    - "hello world from devops-ws"
