apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world
spec:
  steps:
    - name: echo
      image: alpine
      command:
        - echo
      args:
        - "hello world from rick"
